#pragma once

#include "StatusSetter.h"

class StatusSetter16 : public StatusSetter
{
public:
    bool isCarrierOverridden() override;
    std::string getCarrierOverride() override;
    void setCarrier(std::string text) override;
    void unsetCarrier() override;
    bool isSecondaryCarrierOverridden() override;
    std::string getSecondaryCarrierOverride() override;
    void setSecondaryCarrier(std::string text) override;
    void unsetSecondaryCarrier() override;
    bool isPrimaryServiceBadgeOverridden() override;
    std::string getPrimaryServiceBadgeOverride() override;
    void setPrimaryServiceBadge(std::string text) override;
    void unsetPrimaryServiceBadge() override;
    bool isSecondaryServiceBadgeOverridden() override;
    std::string getSecondaryServiceBadgeOverride() override;
    void setSecondaryServiceBadge(std::string text) override;
    void unsetSecondaryServiceBadge() override;
    bool isDateOverridden() override;
    std::string getDateOverride() override;
    void setDate(std::string text) override;
    void unsetDate() override;
    bool isTimeOverridden() override;
    std::string getTimeOverride() override;
    void setTime(std::string text) override;
    void unsetTime() override;
    bool isBatteryDetailOverridden() override;
    std::string getBatteryDetailOverride() override;
    void setBatteryDetail(std::string text) override;
    void unsetBatteryDetail() override;
    bool isCrumbOverridden() override;
    std::string getCrumbOverride() override;
    void setCrumb(std::string text) override;
    void unsetCrumb() override;
    bool isCellularServiceOverridden() override;
    bool getCellularServiceOverride() override;
    void setCellularService(bool shown) override;
    void unsetCellularService() override;
    bool isSecondaryCellularServiceOverridden() override;
    bool getSecondaryCellularServiceOverride() override;
    void setSecondaryCellularService(bool shown) override;
    void unsetSecondaryCellularService() override;
    bool isDataNetworkTypeOverridden() override;
    int getDataNetworkTypeOverride() override;
    void setDataNetworkType(int id) override;
    void unsetDataNetworkType() override;
    bool isSecondaryDataNetworkTypeOverridden() override;
    int getSecondaryDataNetworkTypeOverride() override;
    void setSecondaryDataNetworkType(int id) override;
    void unsetSecondaryDataNetworkType() override;
    bool isBatteryCapacityOverridden() override;
    int getBatteryCapacityOverride() override;
    void setBatteryCapacity(int id) override;
    void unsetBatteryCapacity() override;
    bool isWiFiSignalStrengthBarsOverridden() override;
    int getWiFiSignalStrengthBarsOverride() override;
    void setWiFiSignalStrengthBars(int id) override;
    void unsetWiFiSignalStrengthBars() override;
    bool isGSMSignalStrengthBarsOverridden() override;
    int getGSMSignalStrengthBarsOverride() override;
    void setGSMSignalStrengthBars(int id) override;
    void unsetGSMSignalStrengthBars() override;
    bool isSecondaryGSMSignalStrengthBarsOverridden() override;
    int getSecondaryGSMSignalStrengthBarsOverride() override;
    void setSecondaryGSMSignalStrengthBars(int id) override;
    void unsetSecondaryGSMSignalStrengthBars() override;
    bool isRawWiFiSignalShown() override;
    void showRawWiFiSignal(bool shown) override;
    bool isRawGSMSignalShown() override;
    void showRawGSMSignal(bool shown) override;
    bool isDNDHidden() override;
    void hideDND(bool hidden) override;
    bool isAirplaneHidden() override;
    void hideAirplane(bool hidden) override;
    bool isCellHidden() override;
    void hideCell(bool hidden) override;
    bool isWiFiHidden() override;
    void hideWiFi(bool hidden) override;
    bool isBatteryHidden() override;
    void hideBattery(bool hidden) override;
    bool isBluetoothHidden() override;
    void hideBluetooth(bool hidden) override;
    bool isAlarmHidden() override;
    void hideAlarm(bool hidden) override;
    bool isLocationHidden() override;
    void hideLocation(bool hidden) override;
    bool isRotationHidden() override;
    void hideRotation(bool hidden) override;
    bool isAirPlayHidden() override;
    void hideAirPlay(bool hidden) override;
    bool isCarPlayHidden() override;
    void hideCarPlay(bool hidden) override;
    bool isVPNHidden() override;
    void hideVPN(bool hidden) override;
};
